Decode the response as untyped JSON
The `cometbftClient.Status()` tries to decode the response with some
hardcoded tags, which don't include the one used by Polygon Heimdall
(v2), and therefore making Blazar fail on the post upgrade check:

```
Post-upgrade check failed

error: post upgrade upgrade-block-signed check failed: Could not get
node status: error in json rpc client, with http response metadata:
(Status: 200 OK, Protocol HTTP/1.1). error unmarshalling result:
unknown type "cometbft/PubKeySecp256k1eth"
```

This patch avoids matching the type, as we don't really need it.